version: "3"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python ./src/indicaa-api/manage.py migrate && python ./src/indicaa-api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
        - DB_HOST=db:5432
        - DB_NAME=DB_NAME
        - DB_PASSWORD=DB_PASS
        - DB_USER=DB_USER
  db:
      image: postgres:13
      container_name: indicaa-postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_HOST=db
        - POSTGRES_NAME=DB_NAME
        - POSTGRES_PASSWORD=DB_PASS
        - POSTGRES_USER=DB_USER
        - POSTGRES_DB=postgres
        - POSTGRES_PORT=5432
      volumes:
        - ./db:/var/lib/postgresql/data/