<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-22 21:42
=======
# Generated by Django 4.0.3 on 2022-04-23 15:52
>>>>>>> origin/develop

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_materia_cargahoraria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cargaHoraria',
<<<<<<< HEAD
            field=models.CharField(max_length=255),
=======
            field=models.CharField(max_length=50),
>>>>>>> origin/develop
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigoMateria',
<<<<<<< HEAD
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
=======
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
>>>>>>> origin/develop
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigoTurma',
<<<<<<< HEAD
            field=models.CharField(max_length=255),
=======
            field=models.CharField(max_length=50),
>>>>>>> origin/develop
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario',
<<<<<<< HEAD
            field=models.CharField(max_length=255),
=======
            field=models.CharField(max_length=170),
>>>>>>> origin/develop
        ),
    ]
