# Generated by Django 4.0.3 on 2022-03-31 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_materia_delete_curso_alter_departamento_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='name',
            new_name='nome',
        ),
    ]
