# Generated by Django 4.0.3 on 2022-03-31 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_rename_name_departamento_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=255, unique=True)),
                ('codigoTurma', models.CharField(max_length=2, unique=True)),
                ('horario', models.CharField(max_length=20)),
                ('vagasOfertadas', models.IntegerField()),
                ('vagasOcupadas', models.IntegerField()),
                ('local', models.CharField(max_length=255)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapi.materia')),
            ],
        ),
    ]
