# Generated by Django 4.0.3 on 2022-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='id',
        ),
        migrations.AddField(
            model_name='turma',
            name='idTurma',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
