# Generated by Django 4.0.3 on 2022-03-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_remove_turma_id_turma_idturma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idPeriodo', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('semestre', models.IntegerField(unique=True)),
                ('ano', models.IntegerField(unique=True)),
            ],
        ),
    ]
