# Generated by Django 4.0.3 on 2022-03-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='idPeriodo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='idTurma',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='semestre',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigoTurma',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
