# Generated by Django 4.0.3 on 2022-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_periodo_idperiodo_remove_turma_idturma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='idPeriodo',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='idTurma',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='semestre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.CharField(max_length=255),
        ),
    ]
