# Generated by Django 4.0.3 on 2022-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_periodo_idperiodo_turma_idturma_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periodo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='idTurma',
        ),
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='docente',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
