# Generated by Django 4.0.3 on 2022-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_delete_periodo_remove_turma_idturma_turma_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(default=None),
        ),
    ]
