# Generated by Django 4.0.3 on 2022-03-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_alter_turma_ano_alter_turma_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='semestre',
        ),
    ]
