# Generated by Django 4.0.3 on 2022-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_remove_turma_ano_remove_turma_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(default=None),
        ),
    ]
