# Generated by Django 4.0.3 on 2022-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_turma_ano_turma_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
