# Generated by Django 4.0.3 on 2022-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_turma_idturma_alter_turma_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='idTurma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
